image: gradle:8.11.1-jdk17-alpine

variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
  JIB_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  PROFILE_ACTIVE: $CI_COMMIT_REF_NAME
  JWT_ENC_PWD: $JWT_ENC_PWD
  JASYPT_ENCRYPTOR_PASSWORD: $DEV_ENC_PWD

stages:
  - build
  - deploy

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .gradle/wrapper/
    - .gradle/caches/

build:
  stage: build
  script:
    - ./gradlew clean jib
  only:
    - main
    - dev
  interruptible: true

deploy:
  stage: deploy
  needs:
    - job: build
  variables:
    DOCKER_LATEST_IMAGE_NAME: $CI_REGISTRY_IMAGE:latest
    CONTAINER_NAME: $CI_PROJECT_NAME-$CI_COMMIT_REF_NAME
  before_script:
    - docker login $CI_REGISTRY -u $TOKEN_USER --password $TOKEN_PWD
  script:
    - docker pull $DOCKER_LATEST_IMAGE_NAME
    - docker stop $CONTAINER_NAME;echo $?
    - docker rm -f $CONTAINER_NAME;echo $?
    - docker run -d -p 50051:50051 -v C:\service\planverse:/planverse --restart=unless-stopped --name $CONTAINER_NAME $DOCKER_LATEST_IMAGE_NAME
    - docker system prune -f
  after_script:
    - docker logout
  tags:
    - winos
  only:
    - main
    - dev
  interruptible: true