server:
  port: ENC(bH0UGgoiTTXNZ0OXnnhrqpX0//Z9SyjPJGOR8T76uzgtWUoSZ8/rZzSdseW+rlTP)

spring:
  datasource:
    write:
      jdbc-url: ENC(PxQYo/4lKNiWZZSA1RRq7cmUuTJMESiolZPd0WGYQvdOzIqcSQaoD+EzIz9yZsnOekUeYdg9Z0bjw3N7Af+xr68EppE8uBWVILLgfznN+7IWhh9B32zuOGtjnGEkVnfJ2fz8dsRkxihVk6fSh0vWmUfx2X/4e3fmhlfEM6l7M+FHuZNwbfr5ppEbi0/oDMUde6QnLNRlrQtCYdg0/JKFuw==)
      username: ENC(13NqhGjRn/6aDgmxzPD3gg1vGomMYD+UkQQjavnghVYmqGNW5YwLbW7Ku0pN1Asc)
      password: ENC(bfGz+iJC/DRUEjuVEgli0OY64Lh6KxtPZH9OZMFTDmUAuD94Dtq7t/HJkZpawJH+)
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      minimum-idle: 10
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      pool-name: WRITE-POOL
    read:
      jdbc-url: ENC(Ocvn0TYNjXi6jZ22hu9gWtoy0duakKbw058XdWjDdsw8xHjctgz4QlI+KhJKhBml)
      username: ENC(n8k3pOn458XQlpru/ycizfiadj/b2k4uNH1LsooIltXYpOMjYX7qYkyGJv5AXLm1spgnPnoRGIjXiSeA9ptvJL6CeiGTNAe/L+SIEWyZAGbLmcD04I+UAlPZt6YqqlyM/yQOmfVZMvTaxNspnIJuzXQR/LD4doQ2RLrVmGZnhSaklXwOgLza+RwwEa6+YFLoFGrWodx9U/u+JoAvNITsVw==)
      password: ENC(c1QwIidkz+S2LtLhQOShXHnfgNQaPMob+3tXF7bSa7Me3kkXMNvyzuea2CMXGbU4)
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      minimum-idle: 5
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      pool-name: READ-POOL
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
  data:
    redis:
      url: ENC(A32vQNlFkXCsSZaiTUTRWgpr2kCQcbUJ5ScJD/GmkonzYSNgTysyZD5sz8zhO8VM)
      port: ENC(KM2nbreUrhkFtIbCSHBrf6Ij5JieuGBKXFA/H67XP2IJyWoa7ZJ4Fk7PGiMO+TR5)

logging:
  level:
    org:
      springframework: info