spring:
  datasource:
    url: ENC(wrbzQ7XR5wS+nmfNsx1wRUfVNjNpuVx6NTSHAtQmhdLI4pTgWJOhv3UksULuuheJPJn/DUx/gHdb5LNk297phqjm5k0k1fZud2HJxO7zbzB+EZexdKy8wWfgubKq9CLyrMd7WT33xOh3VTCnT1l0RSw2lzZS0Sr31+S36jQAYhW+pIIpgifhmqhLDb26PLbCUK1aXG0yjac6sWAJJGmP64L+0nQ0+S6FVcN/6VLZG3DykwGewUow/Yk41BmGuCHkOuaD0QaXCL6+7HcDiCKPbA==)
    username: ENC(FDExmQTUr41sQnblCeN+qsTXMQ7Dq1JXAn75Mv4d29T1S1UN5SExsBlQzLa7en9YlP4qCSkcxZ0qPYdiZTHpPQ==)
    password: ENC(IKd25uNvbfX++fp4RwILPRbE1vekeZSn2d/qwlfhduOdOe/HtGZMWmBTSBYd4qdv)
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
  data:
    redis:
      url: localhost
      port: 6379

logging:
  level:
    org:
      springframework: debug