server:
  servlet:
    context-path: /api/v1/
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 600m
      cookie:
        name: JSESSIONID
        secure: true
        http-only: true
        max-age: 600m
  shutdown: graceful
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
  http2:
    enabled: true

spring:
  application:
    name: planverse
  config:
    import: optional:configserver:https://cloud.seoeungi.work

logging:
  config: classpath:spring-logback.xml
  level:
    org:
      springframework:
        session:
          web:
            http:
              SessionRepositoryFilter:
                SESSION_LOGGER: INFO

jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    key-obtention-iterations: 10000
    pool-size: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: none
    health:
      show-details: always
  health:
    db:
      enabled: false
      ignore-routing-data-sources: false
    influxdb:
      enabled: false
    redis:
      enabled: false
    mail:
      enabled: false
    ssl:
      enabled: false